### PR TITLE
Ignore non postmate message during handshake

### PR DESCRIPTION
**Pull request by dboskovic**
If a message is received that does not have a postmate payload, it will break the handshake. This is likely the cause of #29 and #31. It's difficult to add a test for this since it only fails if the message happens exactly in between the handshake.

Below is an example of the handshake failing due to a `webpackOk` event.

image

### CODE REVIEW

**Comment by dboskovic** [comment]
@yowainwright @jakiestfu Not sure if you want the build file added in the PR. The minor dep changes are due to some bit-rot with rollup (https://github.com/Permutatrix/rollup-stream/issues/19) and a missing babel dep.

I'm not sure why build changed the files size by a kb for my condition. Let me know if you'd like anything revised here.

**Comment by jakiestfu** [comment]
Would you mind doing a little investigating with regards to the additional kb?

**Comment by eyalcohen4** [comment]
Hey, we really need this pull request to be merged. How can we help?
cc @dboskovic

**Comment by dboskovic** [comment]
@eyalcohen4 the only weird thing was the full kb increase in size of the compiled file (or at least the size that was published to the readme). Not sure what to do there. There's nothing other than `gulp build` that I can see for doing this. 🤔

**Comment by dboskovic** [comment]
@jakiestfu after a little research I think it's related to the `"external-helpers"` plugin for babel. Since it wasn't previously in package.json I installed the latest version which may have more helpers than the version you guys last compiled with. I tried rolling it back to the previous major version but it's incompatible with Babel 6. ¯\_(ツ)_/¯

**Comment by yowainwright** [comment]
@dboskovic I think a pr that was merged recently should help rather than hurt. 

Could you rebase please?  🙏

**Comment by dboskovic** [comment]
done!

**Comment by yowainwright** [comment]
@dboskovic please let me know if all is good! Thanks for your patience and time. 🙏

**Pull request merged**
