### PR TITLE
Add classList to iFrame

### PR DESCRIPTION
**Pull request by betocantu93**
```javascript
const handshake = new Postmate({
   container: document.querySelector("body"), // Element to inject frame into
   url: iframeUrl,
   classList: ['classOne', 'classTwo'],
})
```
```html
 <iframe class="classOne classTwo" src="http://localhost:5000/"></iframe>
```

### CODE REVIEW

**Comment by betocantu93** [comment]
This solve #109

**Comment by yowainwright** [comment]
@betocantu93 thanks for this! I’ll look soon!!!

**Comment by betocantu93** [comment]
There is something weird with master branch, which is the one I forked, the child doesn't respond to handshakes as the npm version does, I don't think my commit does any breaking changes, so... I don't know... let me know if anything, thanks...

**Comment by yowainwright** [comment]
@betocantu93 it could a dep thing, I’ll dig quick when I can. 😊

**Comment by betocantu93** [comment]
@yowainwright I updated my PR with master, sorry about the wait too, thanks.

**Comment by betocantu93** [comment]
@yowainwright I decided to give it a try to the tests, I think it's working now (first time doing chai) but I had a rough time haha, it was worth it

**Comment by yowainwright** [comment]
@betocantu93 this will be merged if a few days, FYI. Thanks for your patience.

**Comment by yowainwright** [comment]
@betocantu93 can you fix the merge conflicts? Sorry about that; Fix the 2 lines in `src/postmate.js` and build. Thanks, again!

**Comment by betocantu93** [comment]
@yowainwright yep, I think it's done

**Comment by yowainwright** [comment]
@betocantu93 oh heck, yeah! Thank you!!!

**Pull request merged**
