### PR TITLE
Prevent failure when loading library in node/on server

### PR DESCRIPTION
**Pull request by CMTegner**
`window` doesn't exist in the node runtime, so the class definition will always
fail. Replacing `window.Promise` with `Promise` works because `window` is
implied in the browser. I didn't see any reason to keep a reference to `Promise`
on `Postmate`.

My use-case is universal rendering, where I want to load the same code both on the server and in the client, but only execute the handshake in the client. I need to code to not fail to be able to serve the initial page load, and I'd rather not to conditional imports.

### CODE REVIEW

**Comment by jakiestfu** [comment]
My reasoning was to avoid namespace collision with the `Promise` object. I would like to keep `Postmate.Promise` property available to the end user, but maybe we can remove the `window` property from the reference. For example:

`static Promise = Promise;` instead of `window.Promise`. Thoughts?

**Comment by sslash** [comment]
I too see no reason to have Promise on the Postmate namespace. Promise is expected globally in an es6 environment

**Comment by jakiestfu** [comment]
This means the user must override the Promise namespace before they include Postmate. That is, if they want a polyfill. No?

**Comment by CMTegner** [comment]
As I stated in my original comment, "Replacing window.Promise with Promise works because window is implied in the browser". The existing code on `master` requires any `Promise` polyfill/replacement to be loaded before `postmate` is even required (i.e. even before it's used). Letting `Promise` implicitly reference `window` at invocation-time makes `postmate` order-independent, which is exactly what you want. The only time this could pose a problem is if `postmate` is used before *and* after a `Promise` polyfill is loaded, which could case differing behaviour between `postmate` instances. I believe this to be a very unlikely edge-case.

>My reasoning was to avoid namespace collision with the Promise object.

I can't think of a case where you would want the global `Promise` object to be different than what your libraries are using. If you're loading a polyfill/replacement you most likely want this to be used everywhere, not just as `window.Promise`.

**Comment by CMTegner** [comment]
I originally didn't want to update anything in `build/*`, since I usually leave that up to whoever publishes to `npm` (since building and publishing usually goes hand in hand). However, I now realises that the tests are run on the built files, so I actually *have* to update them to make the build pass. I rebased against master, so this should be good to merge.

**Comment by jakiestfu** [comment]
Thanks for sharing your insight, @CMTegner @sslash. I will be resolving this issue later today, appreciate it!

**Comment by CMTegner** [comment]
Want me to rebase again?

Remember that this will be a breaking change, so make sure to bump the major version if you decide to merge and cut a release. I can update the documentation in this PR if you like.

**Comment by jakiestfu** [comment]
We still have a need to specify the replacement for `Promise` without wanting to use a polyfill. That being said, this should be enough of a fix to not cause errors with your setup. Can either of you verify, @CMTegner @sslash ?

Version 1.0.5 -> 0abf212d143c900ececb1495c0186df3c750d133

**Pull request closed without merging**
